steps:
  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:node-16.10.0'
    args: ['install']

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm:node-16.10.0'
    args: ['run', 'build:qa']

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=qa']
