steps:
  # Install node packages
  - name: node:16.10.0
    entrypoint: npm
    args: ['install']

  # Build productive files
  - name: node:16.10.0
    entrypoint: npm
    args: ['run', 'build:$_ENVIRONMENT']

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: apps/noise-to-help
    args: ['app', 'deploy', '--version=$_ENVIRONMENT']
